# Generated by Django 4.1.5 on 2023-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='other_names',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='cover',
            field=models.ImageField(default='', upload_to='Hospital/'),
        ),
    ]
