# Generated by Django 4.1.5 on 2023-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_hospital_other_names_alter_hospital_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='other_names',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='cover',
            field=models.ImageField(default='/hospitals/default.png', upload_to='hospitals/'),
        ),
    ]
